### ISSUE TITLE
Error in-game Tapper 

### ISSUE THREAD

**Issue by psasin36156** [YarmolenkoD/moonbix#16]
![Screenshot 2024-09-24 132420](https://github.com/user-attachments/assets/b6defa11-022b-4932-b1c1-32a29dfca7a4)

Reward task claiming point all good . but error in game tapper.

------
raceback (most recent call last):
  File "C:\Users\preem\Desktop\sybil-airdrop\moonbix-bot\bot\core\tapper.py", line 677, in run
    await self.play_game(session)
  File "C:\Users\preem\Desktop\sybil-airdrop\moonbix-bot\bot\core\tapper.py", line 610, in play_game
    self.complete_game(session)
  File "C:\Users\preem\Desktop\sybil-airdrop\moonbix-bot\bot\core\tapper.py", line 571, in complete_game
    if data_['success']:
KeyError: 'success'
2024-09-24 13:23:28 | ERROR    | 688 - DAD6350 | Unknown error: 'success'
Traceback (most recent call last):
  File "C:\Users\preem\Desktop\sybil-airdrop\moonbix-bot\bot\core\tapper.py", line 677, in run
    await self.play_game(session)
  File "C:\Users\preem\Desktop\sybil-airdrop\moonbix-bot\bot\core\tapper.py", line 610, in play_game
    self.complete_game(session)
  File "C:\Users\preem\Desktop\sybil-airdrop\moonbix-bot\bot\core\tapper.py", line 571, in complete_game
    if data_['success']:
KeyError: 'success'

----------------------

**Comment by YarmolenkoD** [comment]
@psasin36156 I think you use not my bot, I have other logs styles :) 
Please install my bot from my repository and check it :) 

https://github.com/YarmolenkoD/moonbix

**Comment by psasin36156** [comment]
sorry my bad 🥺. i have two folder of moonbix bot lol
