### ISSUE TITLE
run error

### ISSUE THREAD

**Issue by daizheng-code** [YarmolenkoD/moonbix#2]
Traceback (most recent call last):
  File "C:\Users\dz\Desktop\新建文件夹 (3)\moonbix-master\main.py", line 4, in <module>
    from bot.utils.launcher import process
  File "C:\Users\dz\Desktop\新建文件夹 (3)\moonbix-master\bot\utils\__init__.py", line 2, in <module>
    from . import launcher
  File "C:\Users\dz\Desktop\新建文件夹 (3)\moonbix-master\bot\utils\launcher.py", line 12, in <module>
    from bot.core.tapper import run_tapper
  File "C:\Users\dz\Desktop\新建文件夹 (3)\moonbix-master\bot\core\tapper.py", line 225
    json=json_data

SyntaxError: invalid syntax. Perhaps you forgot a comma?

**Comment by 0xTaaa** [comment]
check my pull request, it just add comma on line 225
