### ISSUE TITLE
It doesn't run

### ISSUE THREAD

**Issue by qazzaq666** [YarmolenkoD/moonbix#49]
```
 sh run.sh                    ✘ INT root@hiplet-12810
Activating virtual environment...
run.sh: 9: source: not found
Dependencies already installed, skipping installation.
Skipping .env copying
Reinitialized existing Git repository in /root/moonbix/.git/
error: remote origin already exists.
No local changes to save
Already up to date.
No stash entries found.
Starting the bot...
Traceback (most recent call last):
  File "/root/moonbix/main.py", line 13, in <module>
    asyncio.run(main())
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/root/moonbix/main.py", line 8, in main
    await process()
  File "/root/moonbix/bot/utils/launcher.py", line 93, in process
    logger.info(f"Detected {len(get_session_names())} sessions | {len(get_proxies())} proxies")
  File "/root/moonbix/bot/utils/launcher.py", line 57, in get_proxies
    proxies = [Proxy.from_str(proxy=row.strip()).as_url for row in file]
  File "/root/moonbix/bot/utils/launcher.py", line 57, in <listcomp>
    proxies = [Proxy.from_str(proxy=row.strip()).as_url for row in file]
  File "/usr/local/lib/python3.10/dist-packages/better_proxy/proxy.py", line 52, in from_str
    raise ValueError(f'Unsupported proxy format: {proxy}')
ValueError: Unsupported proxy format: type://user:pass@ip:port
done
PLEASE EDIT .ENV FILE
```

**Comment by BeeObbie07** [comment]
have you fill API_ID and API_HASH one .env file?

**Comment by qazzaq666** [comment]
Yep

**Comment by root2din** [comment]
same error

**Comment by root2din** [comment]
a. ok. solved. use proxy = False
